# Generated by Django 5.2.1 on 2025-06-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.component', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='recipecomponent',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='components',
            field=models.ManyToManyField(through='recipes.RecipeComponent', to='recipes.component', verbose_name='Состав'),
        ),
    ]
